//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthRegistries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HealthRegistries.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;HCIM_IN_FindCandidates xmlns=&quot;urn:hl7-org:v3&quot; xmlns:mif=&quot;urn:hl7-org:v3/mif&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///	&lt;!-- unique id for the message --&gt;
        ///	&lt;id root=&quot;2.16.840.1.113883.3.51.1.1.1&quot; extension=&quot;&quot;/&gt;
        ///	&lt;!-- message creation time --&gt;
        ///	&lt;creationTime value=&quot;&quot;/&gt;
        ///	&lt;!-- message version --&gt;
        ///	&lt;versionCode code=&quot;V3PR1&quot;/&gt;
        ///	&lt;!-- interaction id --&gt;
        ///	&lt;interactionId root=&quot;2.16.840.1.113883.3.51.1.1.2&quot; extension=&quot;HCIM_IN_FindCandidates&quot;/&gt;
        ///	&lt;!-- proce [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FindCandidatesRequest {
            get {
                return ResourceManager.GetString("FindCandidatesRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;HCIM_IN_FindCandidates xmlns=&quot;urn:hl7-org:v3&quot; xmlns:mif=&quot;urn:hl7-org:v3/mif&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///	&lt;!-- unique id for the message --&gt;
        ///	&lt;id root=&quot;2.16.840.1.113883.3.51.1.1.1&quot; extension=&quot;419E8980-8D02-4402-B43D-6A32575B12EF&quot;/&gt;
        ///	&lt;!-- message creation time --&gt;
        ///	&lt;creationTime value=&quot;20120221000000&quot;/&gt;
        ///	&lt;!-- message version --&gt;
        ///	&lt;versionCode code=&quot;V3PR1&quot;/&gt;
        ///	&lt;!-- interaction id --&gt;
        ///	&lt;interactionId root=&quot;2.16.840.1.113883.3.51.1.1.2&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FindCandidatesRequest_Populated {
            get {
                return ResourceManager.GetString("FindCandidatesRequest_Populated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;HCIM_IN_FindCandidatesResponse xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;urn:hl7-org:v3&quot;&gt;
        ///  &lt;id root=&quot;2.16.840.1.113883.3.51.1.1.1&quot; extension=&quot;551ee278-4fb4-4a85-a9b3-c7069a66ee45&quot; /&gt;
        ///  &lt;creationTime value=&quot;20120227233520&quot; /&gt;
        ///  &lt;versionCode code=&quot;V3PR1&quot; /&gt;
        ///  &lt;interactionId root=&quot;2.16.840.1.113883.3.51.1.1.2&quot; extension=&quot;HCIM_IN_FindCandidatesResponse&quot; /&gt;
        ///  &lt;processingCode code=&quot;P&quot; /&gt;
        ///  &lt;processingModeCode code=&quot;T&quot; /&gt;
        ///  &lt;acceptAckCode cod [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FindCandidatesResponse {
            get {
                return ResourceManager.GetString("FindCandidatesResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;HCIM_IN_GetDemographics xmlns=&quot;urn:hl7-org:v3&quot; xmlns:mif=&quot;urn:hl7-org:v3/mif&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///	&lt;!-- unique id for the message --&gt;
        ///	&lt;id root=&quot;2.16.840.1.113883.3.51.1.1.1&quot; extension=&quot;&quot;/&gt;
        ///	&lt;!-- message creation time --&gt;
        ///	&lt;creationTime value=&quot;&quot;/&gt;
        ///	&lt;!-- message version --&gt;
        ///	&lt;versionCode code=&quot;V3PR1&quot;/&gt;
        ///	&lt;!-- interaction id --&gt;
        ///	&lt;interactionId root=&quot;2.16.840.1.113883.3.51.1.1.2&quot; extension=&quot;HCIM_IN_GetDemographics&quot;/&gt;
        ///	&lt;!-- pro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetDemographicsRequest {
            get {
                return ResourceManager.GetString("GetDemographicsRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- edited with XML Spy v4.2 U (http://www.xmlspy.com) by Pat Willmott (Sierra Systems Group) --&gt;
        ///&lt;HCIM_IN_GetDemographics xmlns=&quot;urn:hl7-org:v3&quot; xmlns:mif=&quot;urn:hl7-org:v3/mif&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///	&lt;!-- unique id for the message --&gt;
        ///	&lt;id root=&quot;2.16.840.1.113883.3.51.1.1.1&quot; extension=&quot;419E8980-8D02-4402-B43D-6A32575B12EF&quot;/&gt;
        ///	&lt;!-- message creation time --&gt;
        ///	&lt;creationTime value=&quot;20050621000000&quot;/&gt;
        ///	&lt;!-- message version --&gt;
        ///	&lt;vers [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetDemographicsRequestHistory {
            get {
                return ResourceManager.GetString("GetDemographicsRequestHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;HCIM_IN_GetDemographicsResponse xmlns=&quot;urn:hl7-org:v3&quot; xmlns:mif=&quot;urn:hl7-org:v3/mif&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///	&lt;!-- unique id for the message --&gt;
        ///	&lt;id root=&quot;2.16.840.1.113883.3.51.1.1.1&quot; extension=&quot;419E8980-8D02-4402-B43D-6A32575B12EF&quot;/&gt;
        ///	&lt;!-- message creation time --&gt;
        ///	&lt;creationTime value=&quot;20050621000000&quot;/&gt;
        ///	&lt;!-- message version --&gt;
        ///	&lt;versionCode code=&quot;V3PR1&quot;/&gt;
        ///	&lt;!-- interaction id --&gt;
        ///	&lt;interactionId root=&quot;2.16.840.1.113883.3. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetDemographicsResponse {
            get {
                return ResourceManager.GetString("GetDemographicsResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- edited with XML Spy v4.2 U (http://www.xmlspy.com) by Pat Willmott (Sierra Systems Group) --&gt;
        ///&lt;HCIM_IN_GetDemographicsResponse xmlns=&quot;urn:hl7-org:v3&quot; xmlns:mif=&quot;urn:hl7-org:v3/mif&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///	&lt;!-- unique id for the message --&gt;
        ///	&lt;id root=&quot;2.16.840.1.113883.3.51.1.1.1&quot; extension=&quot;419E8980-8D02-4402-B43D-6A32575B12EF&quot;/&gt;
        ///	&lt;!-- message creation time --&gt;
        ///	&lt;creationTime value=&quot;20050621000000&quot;/&gt;
        ///	&lt;!-- message version --&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetDemographicsResponseHistory {
            get {
                return ResourceManager.GetString("GetDemographicsResponseHistory", resourceCulture);
            }
        }
    }
}
